name: Create Pull Request

on:
  workflow_dispatch:

jobs:
  createPullRequest:
     runs-on: ubuntu-latest

     steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Make changes
          run: |
             echo `date`

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v7
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            title: 'Automated Update'
            body: 'This pull request updates the report file.'
            branch: test-branch-02
            base: test-branch-01 
